# Initialize Flyway if the history table does not exist
flyway.baselineOnMigrate=true

flyway.url=jdbc:sqlserver://localhost:1433;databaseName=demo;trustServerCertificate=true
flyway.user=demo
flyway.password=demo

# Location of the SQL scripts
flyway.locations=filesystem:./migrations,filesystem:./migrations-undo

# NOTE: We do not define the URL, username, or password here.

# Flyway will automatically retrieve them from the environment variables:
# FLYWAY_URL, FLYWAY_USER, and FLYWAY_PASSWORD.
